### ISSUE TITLE
add graph of battery charge over time 

### ISSUE THREAD

**Issue by alanbork** [Core-2-Extreme/Battery_mark_for_3DS#1]
it would be great if you could plot battery charge as a line graph while the app is running. But since it seems to be in "txt" mode, how about instead tweaking the bottom screen output to show the number of minutes:seconds to each 1% charge decrease? Right now it shows the clock (wall time) which is useful too, but the delta would be more helpful for judging if the discharge time is accelerating/decelerating, etc.

**Comment by Core-2-Extreme** [comment]
![00000033](https://user-images.githubusercontent.com/45873899/106357883-474fab80-634c-11eb-8980-9aff13d67a25.png)
Added battery time per 1%.
