### ISSUE TITLE
new datapoints

### ISSUE THREAD

**Issue by alanbork** [Core-2-Extreme/Battery_mark_for_3DS#2]
Here's a new test result for the "database". I just checked a well-used 3dsLL. Not sure how much since I got it used, but it has the original Nintendo batteries.

here are the status from a full check:

min: 0:58, max 5:37, av 3:01, total 4:17. 

The actual run-time was longer than what was estimated after the first few minutes of testing.

**Comment by Core-2-Extreme** [comment]
Thank you for your comment but old version's result is not compatible with v2.0.
so please retest using v2.0.
