### ISSUE TITLE
log file not very easy to parse

### ISSUE THREAD

**Issue by alanbork** [Core-2-Extreme/Battery_mark_for_3DS#3]
The log file could be used to generate nice plots. But as it is currently formatted, no spreadsheet software could ever open it. How about using tabs to separate each data column instead of the mix of [] and spaces?

**Comment by alanbork** [comment]
also what kind of line endings are you using? None of the standard Unicode, ASCII, DOS, formats work. it all ends up on one giant line. Perhaps it's a code-page issue?

**Comment by Core-2-Extreme** [comment]
v2.0 uses csv format.
