### ISSUE TITLE
Additional data-point for 3ds-ll

### ISSUE THREAD

**Issue by alanbork** [Core-2-Extreme/Battery_mark_for_3DS#4]
Another used 3ds-ll (same as xl) with original battery.

min 0:52 max 5:10 av 2:52 total 4:04

after 5 minutes the estimated run-time was closer to 3:30 so this 2nd sample also outlasted the initial estimate.

**Comment by goldeneyeonline** [comment]
Some other devices from my side :-)
Both bought used on ebay:

New 3DS (non-XL!):
min 0:42, avg 2:25, max 4:03
Total Time 97% -> 12% 03:25:49

Old 2DS ("the block" ;-)):
min 1:23, avg  2:57, max 5:45
Total Time 96% -> 11% 04:11:47

GREAT Software btw!

**Comment by alanbork** [comment]
fyi you can edit the readme for the software to add your datapoint to the table of other datapoints.

**Comment by goldeneyeonline** [comment]
Seriously, I need to stop buying these things!!!

New 3DS XL, bought used, good condition, IPS Top-Display:
min 1:25, avg 3:09, max 4:20
Total Time 98% -13% 04:28:41

Seems like a good battery ;-)

**Comment by goldeneyeonline** [comment]
> fyi you can edit the readme for the software to add your datapoint to the table of other datapoints.

Are you sure? It asks me to fork the project, when I try to edit the Readme.md :-/

**Comment by alanbork** [comment]
I was able to edit it without forking and I'm just an annon github user.

**Comment by Core-2-Extreme** [comment]
Thank you for your comment but old version's result is not compatible with v2.0.
so please retest using v2.0.
