### ISSUE TITLE
Where are the results located online?

### ISSUE THREAD

**Issue by Macleykun** [Core-2-Extreme/Battery_mark_for_3DS#5]
I'm running a test on my 3DS for fun, but want to compare it later. I'm curious about the results that people have sent, and want to know where i could find that online :).

**Comment by alanbork** [comment]
There was a list for the previous version but since the dev decided to
change everything :-( it's not comparable any longer.

**Comment by Macleykun** [comment]
it's ok :) i saw later you can get to the list on the 3DS!
Believe my 3ds still hit the top 38 so, i shouldn't complain!

thanks for the update <3 really appricate you taking the time!
