### ISSUE TITLE
Some questions and suggestions

### ISSUE THREAD

**Issue by hreffero** [Core-2-Extreme/Battery_mark_for_3DS#6]
First of all thanks for this awesome homebrew, it's really useful!

- What's the license of the project? Considering bannertool and makerom is included I guess it's MIT License? License is missing from the project page.
- I've tried and QR code download and install with FBI works flawlessly. Do you mind adding a QR code to the releases?

**Comment by Core-2-Extreme** [comment]
Sorry for late reply.

I don't have much knowledge of license, which one should I use?
I want everyone to use my code freely.
ok, I added QR code for .cia in release.

**Comment by thelampsguy** [comment]
I just wanted to throw in my two cents: there's a website called [choosealicense.com](https://choosealicense.com/), run by Github, that tries to give a simple explanation of the many open source licenses out there.

**Comment by Core-2-Extreme** [comment]
I licensed my app as GPL3.
